apiVersion: v2
name: mockoidc
description: A Python implementation of a mock OpenID Connect (OIDC) server for testing and development.
type: application
version: 1.0.2
appVersion: "1.0.2"
keywords:
  - oidc
  - oauth2
  - mock
  - testing
  - authentication
home: https://github.com/marcoimme/mockoidc
sources:
  - https://github.com/marcoimme/mockoidc
maintainers:
  - name: Marco Immediato
    email: marcoimme@gmail.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: oidcmock
      image: marcoimme/oidcmock:latest
